import createFetchClient from "openapi-fetch";
import createQueryClient from "openapi-react-query";
import { PaymentConfig } from "@/lib/payment/config";
import type { paths } from "./schema"; // generated by openapi-typescript

const vaultHeaders = {
  Authorization: PaymentConfig.omise.vaultAuth,
};

export const $omiseVault = createQueryClient(
  createFetchClient<paths>({
    baseUrl: PaymentConfig.omise.vaultBaseUrl,
    headers: vaultHeaders,
  }),
);
export const omiseVault = createFetchClient<paths>({
  baseUrl: PaymentConfig.omise.vaultBaseUrl,
  headers: vaultHeaders,
});
export const $omiseApi = createQueryClient(
  createFetchClient<paths>({
    baseUrl: PaymentConfig.omise.apiBaseUrl,
  }),
);
export const omiseApi = createFetchClient<paths>({
  baseUrl: PaymentConfig.omise.apiBaseUrl,
});
