import type { Metadata } from "next";
import '@fontsource-variable/noto-sans-thai/wght.css';
import '@fontsource-variable/inter/wght.css';
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans")}
    >
      <body className="min-h-full max-w-md w-full flex flex-col mx-auto bg-neutral-100">
        <TooltipProvider>
          {children}
        </TooltipProvider>
      </body>
    </html>
  );
}
