import createFetchClient from "openapi-fetch";
import createQueryClient from "openapi-react-query";
import type { paths } from "./schema"; // generated by openapi-typescript

export const api = createFetchClient<paths>({
  baseUrl: process.env.NEXT_PUBLIC_API_BASEURL ?? "",
});

export const $api = createQueryClient(api);